import { styled } from "@mui/system";

export const DiceWrapper = styled("div")(() => ({
    maxHeight: "100px",
    maxWidth: "100px",
    overflow: "hidden",
    // display: 'none',
    ".shootingStarContainer:nth-child(1)": {
        position: "absolute",
        // width: "100%",
        // height: "130%",
        transform: "rotate(43deg)",
        zIndex: 10,
        overflow: "hidden",
    },
    ".shootingStarContainer:nth-child(2)": {
        position: "absolute",
        // width: "100%",
        // height: "130%",
        transform: "rotate(44deg)",
        zIndex: 10,
        overflow: "hidden",
    },
    ".shootingStarContainer:nth-child(3)": {
        position: "absolute",
        // width: "100%",
        // height: "130%",
        transform: "rotate(43deg)",
        zIndex: 10,
        overflow: "hidden",
    },
    ".shootingStar": {
        position: "absolute",
        height: "1px",
        background: "linear-gradient(-70deg, #ffebeb, black)",
    },
    ".shootingStarContainer:nth-child(1) .shootingStar:nth-child(1)": {
        left: "calc(35%)",
        top: "calc(2%)",
        WebkitAnimation: "shootingFrames 2127ms ease-in-out 11497ms",
        animation: "shootingFrames 2127ms ease-in-out 11497ms",
        opacity: 0.74,
    },
    ".shootingStarContainer:nth-child(1) .shootingStar:nth-child(2)": {
        left: "calc(29%)",
        top: "calc(13%)",
        WebkitAnimation: "shootingFrames 2216ms ease-in-out 60015ms",
        animation: "shootingFrames 2216ms ease-in-out 60015ms",
        opacity: 0.38,
    },
    ".shootingStarContainer:nth-child(1) .shootingStar:nth-child(3)": {
        left: "calc(7%)",
        top: "calc(5%)",
        WebkitAnimation: "shootingFrames 1220ms ease-in-out 34605ms",
        animation: "shootingFrames 1220ms ease-in-out 34605ms",
        opacity: 0.8,
    },
    ".shootingStarContainer:nth-child(1) .shootingStar:nth-child(4)": {
        left: "calc(13%)",
        top: "calc(49%)",
        WebkitAnimation: "shootingFrames 2632ms ease-in-out 34214ms",
        animation: "shootingFrames 2632ms ease-in-out 34214ms",
        opacity: 0.72,
    },
    ".shootingStarContainer:nth-child(1) .shootingStar:nth-child(5)": {
        left: "calc(45%)",
        top: "calc(33%)",
        WebkitAnimation: "shootingFrames 2572ms ease-in-out 47541ms",
        animation: "shootingFrames 2572ms ease-in-out 47541ms",
        opacity: 0.73,
    },
    ".shootingStarContainer:nth-child(1) .shootingStar:nth-child(6)": {
        left: "calc(9%)",
        top: "calc(96%)",
        WebkitAnimation: "shootingFrames 2428ms ease-in-out 34589ms",
        animation: "shootingFrames 2428ms ease-in-out 34589ms",
        opacity: 0.36,
    },
    ".shootingStarContainer:nth-child(1) .shootingStar:nth-child(7)": {
        left: "calc(1%)",
        top: "calc(60%)",
        WebkitAnimation: "shootingFrames 2654ms ease-in-out 8359ms",
        animation: "shootingFrames 2654ms ease-in-out 8359ms",
        opacity: 0.88,
    },
    ".shootingStarContainer:nth-child(1) .shootingStar:nth-child(8)": {
        left: "calc(36%)",
        top: "calc(30%)",
        WebkitAnimation: "shootingFrames 1656ms ease-in-out 690ms",
        animation: "shootingFrames 1656ms ease-in-out 690ms",
        opacity: 0.31,
    },
    ".shootingStarContainer:nth-child(1) .shootingStar:nth-child(9)": {
        left: "calc(43%)",
        top: "calc(80%)",
        WebkitAnimation: "shootingFrames 2051ms ease-in-out 56654ms",
        animation: "shootingFrames 2051ms ease-in-out 56654ms",
        opacity: 0.88,
    },
    ".shootingStarContainer:nth-child(1) .shootingStar:nth-child(10)": {
        left: "calc(48%)",
        top: "calc(25%)",
        WebkitAnimation: "shootingFrames 1325ms ease-in-out 18151ms",
        animation: "shootingFrames 1325ms ease-in-out 18151ms",
        opacity: 0.37,
    },
    ".shootingStarContainer:nth-child(2) .shootingStar:nth-child(1)": {
        left: "calc(32%)",
        top: "calc(70%)",
        WebkitAnimation: "shootingFrames 1510ms ease-in-out 47456ms",
        animation: "shootingFrames 1510ms ease-in-out 47456ms",
        opacity: 0.77,
    },
    ".shootingStarContainer:nth-child(2) .shootingStar:nth-child(2)": {
        left: "calc(9%)",
        top: "calc(7%)",
        WebkitAnimation: "shootingFrames 1640ms ease-in-out 45567ms",
        animation: "shootingFrames 1640ms ease-in-out 45567ms",
        opacity: 0.32,
    },
    ".shootingStarContainer:nth-child(2) .shootingStar:nth-child(3)": {
        left: "calc(41%)",
        top: "calc(89%)",
        WebkitAnimation: "shootingFrames 2497ms ease-in-out 8363ms",
        animation: "shootingFrames 2497ms ease-in-out 8363ms",
        opacity: 0.79,
    },
    ".shootingStarContainer:nth-child(2) .shootingStar:nth-child(4)": {
        left: "calc(16%)",
        top: "calc(97%)",
        WebkitAnimation: "shootingFrames 2259ms ease-in-out 38444ms",
        animation: "shootingFrames 2259ms ease-in-out 38444ms",
        opacity: 0.84,
    },
    ".shootingStarContainer:nth-child(2) .shootingStar:nth-child(5)": {
        left: "calc(47%)",
        top: "calc(82%)",
        WebkitAnimation: "shootingFrames 2610ms ease-in-out 18196ms",
        animation: "shootingFrames 2610ms ease-in-out 18196ms",
        opacity: 0.51,
    },
    ".shootingStarContainer:nth-child(2) .shootingStar:nth-child(6)": {
        left: "calc(39%)",
        top: "calc(75%)",
        WebkitAnimation: "shootingFrames 1521ms ease-in-out 55805ms",
        animation: "shootingFrames 1521ms ease-in-out 55805ms",
        opacity: 0.72,
    },
    ".shootingStarContainer:nth-child(2) .shootingStar:nth-child(7)": {
        left: "calc(45%)",
        top: "calc(11%)",
        WebkitAnimation: "shootingFrames 2669ms ease-in-out 8158ms",
        animation: "shootingFrames 2669ms ease-in-out 8158ms",
        opacity: 0.16,
    },
    ".shootingStarContainer:nth-child(2) .shootingStar:nth-child(8)": {
        left: "calc(13%)",
        top: "calc(62%)",
        WebkitAnimation: "shootingFrames 2135ms ease-in-out 20378ms",
        animation: "shootingFrames 2135ms ease-in-out 20378ms",
        opacity: 0.85,
    },
    ".shootingStarContainer:nth-child(2) .shootingStar:nth-child(9)": {
        left: "calc(7%)",
        top: "calc(64%)",
        WebkitAnimation: "shootingFrames 786ms ease-in-out 47355ms",
        animation: "shootingFrames 786ms ease-in-out 47355ms",
        opacity: 0.72,
    },
    ".shootingStarContainer:nth-child(2) .shootingStar:nth-child(10)": {
        left: "calc(49%)",
        top: "calc(15%)",
        WebkitAnimation: "shootingFrames 1617ms ease-in-out 43407ms",
        animation: "shootingFrames 1617ms ease-in-out 43407ms",
        opacity: 0.26,
    },
    ".shootingStarContainer:nth-child(3) .shootingStar:nth-child(1)": {
        left: "calc(27%)",
        top: "calc(8%)",
        WebkitAnimation: "shootingFrames 1002ms ease-in-out 35471ms",
        animation: "shootingFrames 1002ms ease-in-out 35471ms",
        opacity: 0.9,
    },
    ".shootingStarContainer:nth-child(3) .shootingStar:nth-child(2)": {
        left: "calc(35%)",
        top: "calc(56%)",
        WebkitAnimation: "shootingFrames 1566ms ease-in-out 58510ms",
        animation: "shootingFrames 1566ms ease-in-out 58510ms",
        opacity: 0.73,
    },
    ".shootingStarContainer:nth-child(3) .shootingStar:nth-child(3)": {
        left: "calc(25%)",
        top: "calc(97%)",
        WebkitAnimation: "shootingFrames 1372ms ease-in-out 13192ms",
        animation: "shootingFrames 1372ms ease-in-out 13192ms",
        opacity: 0.9,
    },
    ".shootingStarContainer:nth-child(3) .shootingStar:nth-child(4)": {
        left: "calc(47%)",
        top: "calc(78%)",
        WebkitAnimation: "shootingFrames 2097ms ease-in-out 51575ms",
        animation: "shootingFrames 2097ms ease-in-out 51575ms",
        opacity: 0.26,
    },
    ".shootingStarContainer:nth-child(3) .shootingStar:nth-child(5)": {
        left: "calc(49%)",
        top: "calc(95%)",
        WebkitAnimation: "shootingFrames 1025ms ease-in-out 1394ms",
        animation: "shootingFrames 1025ms ease-in-out 1394ms",
        opacity: 0.86,
    },
    ".shootingStarContainer:nth-child(3) .shootingStar:nth-child(6)": {
        left: "calc(42%)",
        top: "calc(5%)",
        WebkitAnimation: "shootingFrames 1545ms ease-in-out 31920ms",
        animation: "shootingFrames 1545ms ease-in-out 31920ms",
        opacity: 0.66,
    },
    ".shootingStarContainer:nth-child(3) .shootingStar:nth-child(7)": {
        left: "calc(39%)",
        top: "calc(94%)",
        WebkitAnimation: "shootingFrames 1883ms ease-in-out 20174ms",
        animation: "shootingFrames 1883ms ease-in-out 20174ms",
        opacity: 0.57,
    },
    ".shootingStarContainer:nth-child(3) .shootingStar:nth-child(8)": {
        left: "calc(38%)",
        top: "calc(90%)",
        WebkitAnimation: "shootingFrames 2235ms ease-in-out 982ms",
        animation: "shootingFrames 2235ms ease-in-out 982ms",
        opacity: 0.51,
    },
    ".shootingStarContainer:nth-child(3) .shootingStar:nth-child(9)": {
        left: "calc(6%)",
        top: "calc(32%)",
        WebkitAnimation: "shootingFrames 2390ms ease-in-out 47811ms",
        animation: "shootingFrames 2390ms ease-in-out 47811ms",
        opacity: 0.48,
    },
    ".shootingStarContainer:nth-child(3) .shootingStar:nth-child(10)": {
        left: "calc(13%)",
        top: "calc(8%)",
        WebkitAnimation: "shootingFrames 1575ms ease-in-out 47088ms",
        animation: "shootingFrames 1575ms ease-in-out 47088ms",
        opacity: 0.81,
    },
    "@-webkit-keyframes shootingFrames": {
        "0%": { transform: "translateX(0)", width: "0" },
        "30%": { width: "200px" },
        "100%": { width: "0", transform: "translateX(806px)" },
    },
    "@keyframes shootingFrames": {
        "0%": { transform: "translateX(0)", width: "0" },
        "30%": { width: "200px" },
        "100%": { width: "0", transform: "translateX(806px)" },
    },
    ".stars, .twinkleMask, .twinkleMask2, .clouds": {
        position: "absolute",
        top: "0",
        left: "0",
        right: "0",
        bottom: "0",
        width: "100%",
        height: "100%",
        display: "block",
    },
    ".stars": {
        background:
            '#000 url("https://wolf.drjm.co.uk/nightsky/stars.jpg") repeat top center',
        zIndex: 0,
    },
    ".twinkleMask": {
        background:
            'transparent url("https://wolf.drjm.co.uk/nightsky/twinklemask.png") repeat top center',
        zIndex: 1,
        WebkitAnimation: "twinkleFrames 700s linear infinite",
        animation: "twinkleFrames 700s linear infinite",
    },
    ".twinkleMask2": {
        background:
            'transparent url("https://wolf.drjm.co.uk/nightsky/twinkleMask2.png") repeat top center',
        zIndex: 2,
        height: "100%",
        WebkitAnimation: "twinkleFrames2 300s linear infinite",
        animation: "twinkleFrames2 300s linear infinite",
    },
    ".clouds": {
        background:
            'transparent url("https://wolf.drjm.co.uk/nightsky/clouds.png") repeat top center',
        zIndex: 3,
        height: "100%",
        WebkitAnimation: "cloudsFrames 300s linear infinite",
        animation: "cloudsFrames 300s linear infinite",
    },
    ".fogContainer": {
        width: "100%",
        height: "100%",
        overflow: "hidden",
        position: "relative",
        zIndex: 7,
    },
    ".fog": {
        position: "absolute",
        left: "-50%",
        top: "-30%",
        width: "100%",
        height: "100%",
        WebkitAnimationName: "fogFrames",
        animationName: "fogFrames",
        WebkitAnimationDuration: "60s",
        animationDuration: "60s",
        WebkitAnimationTimingFunction: "linear",
        animationTimingFunction: "linear",
        WebkitAnimationIterationCount: "infinite",
        animationIterationCount: "infinite",
        WebkitAnimationDirection: "alternate",
        animationDirection: "alternate",
        background:
            "linear-gradient(-5deg, #00000000 0%, #ffffff15 40%, #74590121 45%, #8b845b21 55%, #00000000 70%)",
    },
    "@-webkit-keyframes fogFrames": {
        "0%": { transform: "none" },
        "10%": { transform: "scaleY(0.75) translate(5%, -2%) rotate(15deg)" },
        "25%": { transform: "scaleY(1) translate(10%, 7%)" },
        "50%": { transform: "scaleY(0.5) rotate(-15deg)" },
        "75%": { transform: "scaleY(0.2) translate(7%, -2%)" },
        "100%": { transform: "none" },
    },
    "@keyframes fogFrames": {
        "0%": { transform: "none" },
        "10%": { transform: "scaleY(0.75) translate(5%, -2%) rotate(15deg)" },
        "25%": { transform: "scaleY(1) translate(10%, 7%)" },
        "50%": { transform: "scaleY(0.5) rotate(-15deg)" },
        "75%": { transform: "scaleY(0.2) translate(7%, -2%)" },
        "100%": { transform: "none" },
    },
    "@-webkit-keyframes twinkleFrames": {
        from: { backgroundPosition: "0 0" },
        to: { backgroundPosition: "-10000px 5000px" },
    },
    "@keyframes twinkleFrames": {
        from: { backgroundPosition: "0 0" },
        to: { backgroundPosition: "-10000px 5000px" },
    },
    "@-webkit-keyframes twinkleFrames2": {
        from: { backgroundPosition: "0 0" },
        to: { backgroundPosition: "10000px 5000px" },
    },
    "@keyframes twinkleFrames2": {
        from: { backgroundPosition: "0 0" },
        to: { backgroundPosition: "10000px 5000px" },
    },
    "@-webkit-keyframes cloudsFrames": {
        from: { backgroundPosition: "0 0" },
        to: { backgroundPosition: "10000px 0" },
    },
    "@keyframes cloudsFrames": {
        from: { backgroundPosition: "0 0" },
        to: { backgroundPosition: "10000px 0" },
    },
}));
